### ISSUE TITLE
Generate tarball release?

### ISSUE THREAD

**Issue by oblute** [martinResearch/DEODR#22]
There are no tarball files released for this package here on GitHub or on PyPi (only wheels). Is it possible to generate/compile one either here or on pypi. Working on building this for conda-forge.

**Comment by martinResearch** [comment]
I am using the library [cibuildwheel](https://github.com/joerick/cibuildwheel) to create the wheels for various python versions and os and I don't know if it can produce the tarball files you are looking for. I am not familiar with how to generate tarball files that have the right structure for conda-forge, maybe could you provide some guidance ?  Which version of python and which os would you want the precompiled conda package to support ?

**Comment by rluria14** [comment]
@oblute @martinResearch this might lead you in the right direction: https://help.github.com/en/enterprise/2.15/user/articles/creating-releases

**Comment by martinResearch** [comment]
I am now calling « python setup.py sdist » in the appveyor ci runs and saving the resulting tar.gz file in the artefacts (for example [here](https://ci.appveyor.com/project/martinResearch/deodr/build/job/s44ibta0o7anh31m/artifacts)) is it the tar.gz file you need ? Automatic  upload of this file pypi file does not work yet.

**Comment by oblute** [comment]
@martinResearch yes, the tar.gz file would be exactly what we need. thank you!

**Comment by martinResearch** [comment]
Does that work for you ? 
https://github.com/martinResearch/DEODR/releases/tag/v0.1.14

**Comment by ndmaxar** [comment]
Hi there, thank you for getting the tarball release out. It's missing one thing in order to build from source.

**Comment by martinResearch** [comment]
@ndmaxar , I udpated the deodr-0.1.14.tar.gz  here https://github.com/martinResearch/DEODR/releases/tag/v0.1.14. Is it working now ?

**Comment by ndmaxar** [comment]
@martinResearch that got me past the one hurdle, but there were more. I've opened a PR with my fixes here: https://github.com/martinResearch/DEODR/pull/28

**Comment by martinResearch** [comment]
@oblute is that solved in #33 ? if so I will close this issue

**Comment by oblute** [comment]
@martinResearch good to go. thanks!
