### ISSUE TITLE
Render Silhouette 

### ISSUE THREAD

**Issue by dihuangdh** [martinResearch/DEODR#24]
Hi, thanks for your awesome work!

Could you tell me how to render silhouette? Seems DEODR doesn't have this feature right now.

**Comment by martinResearch** [comment]
You’re welcome ! 
In order for to draw the silhouette you can render a gray colour image with a black background and render the mesh in white by putting a vector of ones for the vertices colors. It is not the fastest approach to render silhouettes as it will still raster every triangle but you will get the expected silhouette and back propagated gradients (I.e. get non zero gradients only on vertices that are associated to edges that are on the silhouette). I will try to add an example soon.
