### ISSUE TITLE
Render uv-maps

### ISSUE THREAD

**Issue by yangmx2018** [martinResearch/DEODR#26]
Hello.Thanks for your great work！Could u show me how to render uv-maps by DEODR? Thank u.

**Comment by martinResearch** [comment]
Running the function example_channels in DEODR\deodr\examples\render_mesh.py you should be able to see and example of uv image rendering as seen in the lower right image here. You may have to add  the line scene. sigma = 0  in that function to make it work.
 
![image](https://user-images.githubusercontent.com/18285382/86940454-c3796c00-c13a-11ea-90a7-abf7b4f032a4.png)

**Comment by yangmx2018** [comment]
Thank you~
