### ISSUE TITLE
NaN value in the rendered result

### ISSUE THREAD

**Issue by quanhua92** [martinResearch/DEODR#43]
**Describe the bug**
I am working on a custom Renderer with Scene3DPytorch and ColoredTriMeshPytorch. However, I encountered a NaN in the output tensor of the `scene.render` method.
Here is the gist contains my code: [link to code](https://gist.github.com/quanhua92/93d230aca3f4188f3874ffde1e1a956c)
The data for vertices and faces can be download at [link to data](https://drive.google.com/file/d/1-athT5Oy0qx36nxSFesgn1NjlbV3hAy-/view?usp=sharing)

**To Reproduce**
1. Go to [link to code](https://gist.github.com/quanhua92/93d230aca3f4188f3874ffde1e1a956c)
2. Download `vertices.npz` and `faces.npz`:  [link to data](https://drive.google.com/file/d/1-athT5Oy0qx36nxSFesgn1NjlbV3hAy-/view?usp=sharing)
3. Run the script `nanproblem.py`
4. See error:
- You can see that there are 387 nan values in the `img` tensor and the `grad` for the `trans` tensor is also nan
print("nan counts = ", img[torch.isnan(img)].shape) # nan counts =  torch.Size([387])
print("trans grad", trans.grad) # trans grad tensor([nan, nan, nan])

**Expected behavior**
I expected to have a valid gradient in the `trans.grad`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version: 0.1.15 for NaN error. 
I have `AssertionError` on 0.1.17 at `assert self.adjacencies.is_manifold` 
Will update if have NaN error on 0.1.17

**Comment by quanhua92** [comment]
The `vertices` and `faces` are from a model that I am working on [Open3D lib](http://www.open3d.org/docs/latest/python_api/open3d.geometry.TriangleMesh.html).
In DEODR 0.1.17, I can see that `mesh.adjacencies.is_closed` and `mesh.adjacencies.is_manifold` are both `false`.

I used some utility methods from [Open3D lib](http://www.open3d.org/docs/latest/python_api/open3d.geometry.TriangleMesh.html) on my mesh in Open3D and here are some results:
- open3d_mesh.is_watertight() => False
- open3d_mesh.is_vertex_manifold() => False
- open3d_mesh.is_edge_manifold() => True

Can you give me some ideas how to make sure `mesh.adjacencies.is_closed` and `mesh.adjacencies.is_manifold` are `true`? 
Thanks

**Comment by martinResearch** [comment]
Hi, 
I had a look at your mesh in meshlab and there are some non manifold edges. Mesh repairing is out of the score of my library. how was your mesh produced ? could you use a method that would produce watertight surfaces (Poisson reconstruction for example). Otherwise you could try to repair your mesh in meshlab.

**Comment by quanhua92** [comment]
Thanks. I used a neural network to output this mesh. I will find a way to produce watertight surfaces.

**Comment by martinResearch** [comment]
I have PR in progress that adds a method to extract the largest manifold subpart of a mesh using linear programming https://github.com/martinResearch/DEODR/pull/51. However the best approach would be to have an algorithm that generates manifold surfaces in the first place
